### ISSUE TITLE
Error with demo_Toy_Problem 

### ISSUE THREAD

**Issue by susan-sheehan** [jakeret/tf_unet#132]
Hi, I am new to tensorflow, python and machine learning.  I'm finding the learning curve quite steep.  I am attempting to embark on an Image segmentation task and would like to use tf_unet for this.  I am attempting to follow the demo before I switch to my own Images.    Running the jupyter notebook on the demo code I start getting "errors"  at step 7
![image](https://user-images.githubusercontent.com/19174804/32663538-43df881c-c5fc-11e7-8651-6b2fbc864baf.png)
As this isn't much to go on, aside from red highlighting charged ahead when I get to the end of the code.  I get the following 

![image](https://user-images.githubusercontent.com/19174804/32663575-6d29db14-c5fc-11e7-88b9-a73cc693edca.png)

Neither of these errors do I find informative in troubleshooting.  Can someone please help?

**Comment by jakeret** [comment]
Well, this is a lot of ground to cover. I can imagine the step learning
curve.
The red text is not an error but expected output from the logging.

The second issue seems to pop up because a variable has no been computed.
Have you execute all cells ('prediction = net.predict ...')?

On Nov 10, 2017 15:50, "susan-sheehan" <notifications@github.com> wrote:

Hi, I am new to tensorflow, python and machine learning. I'm finding the
learning curve quite steep. I am attempting to embark on an Image
segmentation task and would like to use tf_unet for this. I am attempting
to follow the demo before I switch to my own Images. Running the jupyter
notebook on the demo code I start getting "errors" at step 7
[image: image]
<https://user-images.githubusercontent.com/19174804/32663538-43df881c-c5fc-11e7-8651-6b2fbc864baf.png>
As this isn't much to go on, aside from red highlighting charged ahead when
I get to the end of the code. I get the following

[image: image]
<https://user-images.githubusercontent.com/19174804/32663575-6d29db14-c5fc-11e7-88b9-a73cc693edca.png>

Neither of these errors do I find informative in troubleshooting. Can
someone please help?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jakeret/tf_unet/issues/132>, or mute the thread
