### ISSUE TITLE
how install this with anaconda?

### ISSUE THREAD

**Issue by corelli359** [jakeret/tf_unet#147]
hi,i work python with anaconda,so how can i install under the anaconda~
thanks!

**Comment by UCRajkumar** [comment]
Using your Anaconda navigator, create a new environment, one that uses python 3.5 (youtube it if you don't know how to do this). Then, download necessary packages such as tensorflow etc right in anaconda navigator under the new environment that you just created (you can use the terminal but using the navigator is easier to keep track of which tensorflow version you're downloading with regards to compatibility with the python version). Once again, you might have to google how to do this in Anaconda navigator if you're not already familiar with it.

Then, open one of the ipython notebooks inside the demo folder and run that in Jupyter.

That's the easiest way to get started (at least it was for me).

Otherwise, once you create the new environment, there is an option to open a new terminal using that environment (if you click the play button, it should open up options, once again, you can google this). In this terminal, you can run the python code as you would run any other python code.
