### ISSUE TITLE
Network training on color not on features 

### ISSUE THREAD

**Issue by anilmaddala** [jakeret/tf_unet#207]
I am training the network on segmenting deformable objects like people.

The network seems to train on colors (in this case skin tones) rather than features of the object.

The network is detecting backgounds colors which are similar to skin tones, but not actual people.

Is there a way to train the network to emphasize on features? Should I pre-process the data? right now my training input is RGB image and a binary mask with white for object of interest (person) and black for the rest of the image.

**Comment by jakeret** [comment]
> deformable objects like people

interesting... ;-)

As so often in ML there is no definite solution to a problem. Which means you will have to experiment a bit.
One thing that might be worth investigating is to transform your RGB data into HSV color space as this tends to work better for computer vision task. Maybe you could even try to use gray scale images

**Comment by anilmaddala** [comment]
I tried with with different YUV, HSV and grayscale color formats along with color augmentation. The nnetwork still seems to be looking for the shade of color rather than the features. Any thing else I can try?

**Comment by creatist** [comment]
![image](https://user-images.githubusercontent.com/8329576/46399482-71681300-c72a-11e8-89e3-c0ec2e6984fd.png)
This question can be found in toy_problem, look the picture above. I think color and brightness are  main primary features , texture is one of  superior feature. If the network can not distinguish similar color , try do some data augment on those images.

**Comment by wkeithvan** [comment]
My knee jerk response is this sounds like a data issue. Assuming you can get the UNet to work on something like the toy problem, your problem one of the following:

- Your data isn't varied enough. If you always have Caucasian people on dark background, then skin colour is a pretty good proxy for segmentation. Make sure that your people have different skin tones, hair colour, clothing colour, and that your background is of different colours. If getting this data is difficult, consider trying some data augmentation techniques to change the colours so that colour is no longer a good proxy.
- You don't have enough data. If you don't have enough data, it can be hard for the algorithm to properly generalize away from the first local minimums that make sense. More data is always better, so look into ways to get more training images.

Another idea is to use a pre-trained network that already works on people. I have been messing around with [Mask RCNN](https://arxiv.org/abs/1703.06870) and have used pre-trained weights since they work quite well. Here is a great [YouTube tutorial](https://www.youtube.com/watch?v=2TikTv6PWDw) on setting it up on your end and here is the [GitHub repository](https://github.com/matterport/Mask_RCNN) with all the code. It took me only like an hour to get everything running on my laptop and working with my own personal photos and is really good at detecting people. If you need more categories that the repo provides, consider using transfer learning techniques so you only have to do a little bit of training on the final layers and not start from scratch!
