### ISSUE TITLE
Segmentation with small dataset

### ISSUE THREAD

**Issue by giovanni-turra** [jakeret/tf_unet#56]
Thanks for your work.

I am trying to apply u-net to a small dataset of 16 patches (it is really small but I need to understand if I am doing some mistakes). Specifically, I prepared a binary mask to define what is positive (1) and negative (0).

Unfortunately, I found two problems:

1- If I select a patch without positive elements, the network normalised the prediction probability.
2- Typical negative elements (with completely different colours) are evaluated as positive.

I started from launcher file placed in script folder and change it to evaluate pictures.

To conclude, I use as test the same pictures of training.

Do you have any suggestion?

Thanks,

Giovanni

**Comment by jakeret** [comment]
Sorry for the late reply.

Basically this sound alright what you're doing. Except that the dataset might be to small to train a network. 

If you can, you should try to feed in patches that contain both, positive and negative masks.
Have you checked what happens if you invert the mask? Are you still seeing this weird behavoir?
