### ISSUE TITLE
Conceptual Question

### ISSUE THREAD

**Issue by YadavKapil** [jakeret/tf_unet#64]
Hi,

In the toy problem, if I remove output's 2nd class ( i.e. the output map's NOT class), 
then will the Unet give similar results? 

The reason I am asking this is - I am trying to implement unet for a 6 class problem and there is a high class imbalance towards the 'background' class. So, now I am considering removing the background class from output map (thus, making it a 5 class problem). In this scenario, the pixels corresponding to background class will have 0s in all the other 5 classes. Since, the dice coeff. does not take into account True Negatives for cost calculation, this trick should work out fine.
I am using Dice coeff with Momentum Optimizer and have tried various layers, feature_root combinations. 

But, with this setup, the network is not learning. After some training, the most frequent class becomes white and all other classes become black. The weight histograms are not changing at all as training continues. The gradients are decreasing slowly. And Dice loss is remaining almost constant.

I have been experimenting with this for last 15-20 days. Any help regarding this would make my day. :)

(@jakeret - Since, this issue is not related to technical problems in tf_unet, I will close it after some time if there is no response.)

**Comment by jakeret** [comment]
This is something I have never considered. Franktly, I'm not even sure if this would work (especially for the binary class problem) since the network is expecting a one-hot encoding.

For the multiclass imbalance: There have been successes in addressing this by training one model per class and oversampling the rare classes. A good read regarding this are the sucess stories of the [DSTL Kaggle competion](https://www.kaggle.com/c/dstl-satellite-imagery-feature-detection/discussion).
